name: Deploy to Pinata IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set IPFS Path (Set path to where IPFS is installed)
      - name: Set IPFS Path
        run: |
          echo "Setting IPFS path to C:\Apps\kubo"
          $env:IPFS_PATH = "C:\Apps\kubo\ipfs.exe"
          echo "IPFS path set."

      # Step 3: Verify IPFS CLI Installation using full path
      - name: Verify IPFS CLI Installation
        run: |
          C:\Apps\kubo\ipfs.exe --version

      # Step 4: Add website files to IPFS
      - name: Add website to IPFS
        id: ipfs_add
        run: |
          C:\Apps\kubo\ipfs.exe init
          C:\Apps\kubo\ipfs.exe add -r . > ipfs_hash.txt
          echo "::set-output name=cid::$(tail -n 1 ipfs_hash.txt | awk '{print $2}')"

      # Step 5: Pin the content to Pinata
      - name: Pin to Pinata
        run: |
          curl -X POST "https://api.pinata.cloud/pinning/pinByHash" \
          -H "pinata_api_key: ${{ secrets.PINATA_API_KEY }}" \
          -H "pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{\"hashToPin\":\"${{ steps.ipfs_add.outputs.cid }}\"}"

      # Step 6: Output the IPFS URL
      - name: Output IPFS URL
        run: echo "Website deployed to https://gateway.pinata.cloud/ipfs/${{ steps.ipfs_add.outputs.cid }}"
