name: Deploy to Pinata IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Ensure IPFS CLI is installed (Assuming IPFS is already installed globally on your system)
      - name: Verify IPFS CLI Installation
        run: |
          ipfs --version

      # Step 3: Add website files to IPFS
      - name: Add website to IPFS
        id: ipfs_add
        run: |
          ipfs init
          ipfs add -r . > ipfs_hash.txt
          echo "::set-output name=cid::$(tail -n 1 ipfs_hash.txt | awk '{print $2}')"

      # Step 4: Pin the content to Pinata
      - name: Pin to Pinata
        run: |
          curl -X POST "https://api.pinata.cloud/pinning/pinByHash" \
          -H "pinata_api_key: ${{ secrets.PINATA_API_KEY }}" \
          -H "pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{\"hashToPin\":\"${{ steps.ipfs_add.outputs.cid }}\"}"

      # Step 5: Output the IPFS URL
      - name: Output IPFS URL
        run: echo "Website deployed to https://gateway.pinata.cloud/ipfs/${{ steps.ipfs_add.outputs.cid }}"
